#!/bin/bash
#    Copyright (C) 2013 Thomas Carette


if [ ! -e $1 ]
then
#	echo "Missing file '$1'." > /dev/stderr
	exit 1
fi

nl='
'

if $( grep -q 'Core' $1 )
then
	blstr="$( grep -nA3 "CSF(s):\|\*" $1)"
	bln=$( echo "$blstr" | grep "$(echo $2 | tr -d ' ' )$")
	blstr="$( echo "$blstr" | grep "\*" )"
	if [ "$bln" == '' ]
	then
	  exit 2
	fi
  bln=$(( ${bln%-*} - 3 ))
else
	exit 3
fi

numbl=$( echo "$blstr" | wc -l )

n=0
for bl in $( seq 1 ${numbl} )
do
  tmp=$( echo "$blstr" | head -$bl | tail -1 )
  n=$(( ${tmp%:*} - 1 ))
  if [ $n -ge $bln ]
	then
		break
	fi
done
if [ $n -le $bln ]
then
	n=$( wc -l $1 | awk '{print $1}' )
fi
echo $(( ($n - $bln) / 3 ))
