#!/bin/bash 
#    Copyright (C) 2013 Thomas Carette
###############################################################
TRUE=0
FALSE=1
NO_ARGS=1 
E_OPTERROR=65

VERBOSE=/dev/null

print_help()
{
echo -ne "
weight:\n 
Print the squared summed weight of all Csf of case.c and case.l file
Usage: weight {-hm:v} case\n
Options: -h            : Print this help\n
         -v            : Be verbose
Arguments:\n
           case        : The name of the .l and .c file.\n

"
exit 0
}
  
while getopts "h:v" Option
do
   case $Option in
   h     ) print_help;;
   v     ) VERBOSE=/dev/stdout;;
   *     ) echo "Unimplemented option chosen.";;   # DEFAULT
   esac
done

shift $(($OPTIND - 1))

if [ "$1" = "" ]
then
	echo "Please specify the name of the .l and .c file."
	exit 1
fi

Input_c="$1.c"
Input_l="$1.l"

if [ ! -e $Input_c ]
then
	echo "Missing file '$Input_c'." > /dev/stderr
	exit 1
fi
if [ ! -e $Input_l ]
then
	echo "Missing file '$Input_l'." > /dev/stderr
	exit 1
fi

rm .result &> /dev/null

if [ "$2" != "" ]
then
	gawk '{ if ( FNR %2 ==1 ) { print $0 } }' $2.c | grep ')' | uniq > .ref.weight
else
	gawk '{ if ( FNR %2 ==1 ) { print $0 } }' $1.c | grep ')' | uniq > .ref.weight
fi

if $( grep -q "0\." .ref.weight )
then
  rm bid
  touch bid
  for li in $( seq 1 $( wc .ref.weight | gawk '{print $1}' ) )
  do
    tmp=$( head -${li} .ref.weight | tail -1 )
    lgth=$( echo "8*$( echo $tmp | grep -o ")" | wc | gawk '{print $1}' ) " | bc -l )
    echo "${tmp:0:${lgth}}" >> bid
  done
  cat bid | uniq > .ref.weight
fi

for linenr in $( seq 1 $(( $( cat .ref.weight | wc -l ) )) )
do
	line="$( head -$linenr .ref.weight | tail -1 )"
	
	echo "-----------------------------------------------------" >> $VERBOSE
	echo "${line}" >> $VERBOSE
	name=$line
	
	csfnrall=$( grep -n "$line" $Input_c | cut -d ':' -f1 ) 

	Mrweight=0
	for csfnrdouble in $csfnrall
	do
		csfnr=$(( ($csfnrdouble-1)/2 ))
		entry=$(( $csfnr % 7 ))
		if [ $entry = 0 ]
		then
			entry=7
		fi
		line=$(( ($csfnr-$entry)/7 ))

		weightline="$( head -$(( 7+$line )) $Input_l | tail -1 )"
		weight=$( echo "$weightline" | \
		          cut -c$(( $entry*11-10 ))-$(( $entry*11 )) )
		echo "Csf $csfnr, line $line, entry $entry, mixing $weight" >> $VERBOSE
		Mrweight=$( echo "$Mrweight+($weight*$weight)" | bc -l )
	done

	echo "-----------------------------------------------------" >> $VERBOSE
	echo "Weight total: $( echo "sqrt( $Mrweight ) " | bc -l ) " >> $VERBOSE

	printf "%13.11f %70s\n" \
	       "$( echo "sqrt( $Mrweight ) " | bc -l )" "$name" >> .result

	echo "" >> $VERBOSE

done

Weighttottemp=0
inc=0
sort -r .result > .result1
for i in $( cat .result1 | gawk '{ print $1 }' )
do
  let inc++
  Weighttottemp=$( echo "${Weighttottemp}+${i}^2" | bc -l )
  Weighttot=$( echo "sqrt(${Weighttottemp})" | bc -l )
  Weighttot=${Weighttot:0:13}
  echo "${Weighttot} $( head -${inc} .result1 | tail -1 )"
done

rm .result
rm .result1
rm .ref.weight

exit 0

