#!/bin/bash
#    Copyright (C) 2013 Thomas Carette


#####################################################
#
# Edit this
#
abscisse="3 4 5 6 7 8 9"      # tabulated layers
blocks="_NR _BPCI"            # label of the calculations (e.g. 8_NR)
rel="_RCI"
Js='2'                        # considered Js
operateurs="enc rsmsp Drsmsp rhfsA DrhfsA rhfsB DrhfsB"

#####################################################

source $(which anaGrasp_func.sh)
source $(which anaAtsp2k_func.sh)
source $(which anaRelCorr_func.sh)

for red in ${blocks}
do


title='OP\LAY'

echo '-'

echo "$(\

bid="$(\
for Op in ${operateurs}
do
	echo "$Op & "
done )"

	echo "model &" $bid

for i in ${abscisse}
do
	for J in $Js
	do
		temp=${i}${rel}
		Dtemp=${i}${red}
		echo ${temp} '&' $(\
			for Op in ${operateurs}
			do
				echo "$( ${Op} ${temp} ${J} 1 $Dtemp ${J} 1) &"
			done\
		)
	done
done )" | column -t  | sed 's/& *$/\\\\ /g'
done
