#! /bin/bash -l
#    Copyright (C) 2013 Thomas Carette


HASH='#'

HOME=$(pwd)

for i in *.cm
do

rlevels ${i} >/dev/null 2>&1 || continue

CONFIG=${i%*.cm}

if [ -e ${CONFIG}.ch ]
then
  continue
fi

echo $i

TMP=${TMPDIR}/HFS${1}/${CONFIG}
OUT=${WORKDIR}

n=$(rnrcfg ${CONFIG}.c)

MEM=$(( ${n}/150000 + 1))
FILE=$(( ${MEM} * 10 ))
TIME=$(( ${n}/30000 + 1 ))


echo "
${HASH}!/bin/bash -l
${HASH}PBS -o out
${HASH}PBS -e err
${HASH}PBS -N ${1}rhfs${CONFIG}
${HASH}PBS -l mem=${MEM}gb
${HASH}PBS -l file=${FILE}gb
${HASH}PBS -l walltime=${TIME}:00:00:00

mkdir -p $TMP
cd $TMP

ln -s ${HOME}/isodata .
ln -s ${HOME}/${CONFIG}.c bid.c
ln -s ${HOME}/${CONFIG}.cm bid.cm
ln -s ${HOME}/${CONFIG}.w bid.w

rhfs3 &> ${OUT}/\${PBS_JOBID%*.mn01.usr.hydra.vub.ac.be}.${n}.rhfs.out <<!
y
bid
y
y
y
!
mv bid.ch ${HOME}/${CONFIG}.ch
mv bid.choffd ${HOME}/${CONFIG}.choffd

" > rhfs.sh

touch ${CONFIG}.ch
qsub rhfs.sh

done
