#! /bin/bash -l
#    Copyright (C) 2013 Thomas Carette

HASH='#'

HOME=$(pwd)

for i in *.cm
do

rlevels ${i} >/dev/null 2>&1 || continue

CONFIG=${i%*.cm}

if [ -e ${CONFIG}.sms ]
then
  continue
fi

echo $i

TMP=${TMPDIR}/SMS${1}/${CONFIG}
OUT=${WORKDIR}

n=$(tnrcfg ${CONFIG}.c)

MEM=$(( ${n}/150000 + 1))
FILE=$(( ${MEM} * 10 ))
TIME=$(( ${n}/40000 + 1 ))


echo "
${HASH}!/bin/bash -l
${HASH}PBS -o out
${HASH}PBS -e err
${HASH}PBS -N ${1}bsms${CONFIG}
${HASH}PBS -l mem=${MEM}gb
${HASH}PBS -l file=${FILE}gb
${HASH}PBS -l walltime=${TIME}:00:00:00

mkdir -p $TMP
cd $TMP

ln -s ${HOME}/isodata .
ln -s ${HOME}/${CONFIG}.c bid.c
ln -s ${HOME}/${CONFIG}.cm bid.cm
ln -s ${HOME}/${CONFIG}.w bid.w

sms2 &> ${OUT}/\${PBS_JOBID%*.mn01.usr.hydra.vub.ac.be}.${n}.sms.out <<!
y
bid
y
!
mv bid.ci ${HOME}/${CONFIG}.sms

" > sms.sh

touch ${CONFIG}.sms
qsub sms.sh

done
